#! /bin/bash
#cd ~/docroot/avatars
echo "<html><head><title>Avatars</title></head>">index.html
echo "<body>">>index.html
ls *.png|sort -df|sed "s;.*;<table style="display:inline"><tr><td align=center><a href=&>&<br><img src=& border=0></table>;">>index.html
echo "</body></html>">>index.html

